version: '3'

services: 
  todo_db:
    image: postgres:12
    container_name: todo_db
    volumes: 
      - todo_db:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports: 
      - "5432:5432"
    networks: 
      - todo

volumes: 
  todo_db:
    external: true

networks: 
  todo:
    external: true


